
import { Employee, GridCellDef, PerformanceLevel, PotentialLevel } from './types';

export const GRID_CELLS: GridCellDef[] = [
  // Top Row (High Potential)
  { id: 'enigma', title: '潜力之星 (Enigma)', description: '高潜低绩。如未经琢磨的钻石，需要辅导或调整岗位匹配度。', color: 'text-yellow-700', bg: 'bg-yellow-50', potential: PotentialLevel.High, performance: PerformanceLevel.Low },
  { id: 'growth', title: '成长之星 (Growth)', description: '高潜中绩。核心培养对象，给予挑战性任务。', color: 'text-green-700', bg: 'bg-green-50', potential: PotentialLevel.High, performance: PerformanceLevel.Medium },
  { id: 'star', title: '超级明星 (Super Star)', description: '高潜高绩。企业的未来领袖，应予以重任和晋升保留。', color: 'text-blue-700', bg: 'bg-blue-50', potential: PotentialLevel.High, performance: PerformanceLevel.High },

  // Middle Row (Medium Potential)
  { id: 'dilemma', title: '待激活 (Dilemma)', description: '中潜低绩。需要制定绩效改进计划(PIP)或深入分析原因。', color: 'text-orange-700', bg: 'bg-orange-50', potential: PotentialLevel.Medium, performance: PerformanceLevel.Low },
  { id: 'core', title: '核心骨干 (Core)', description: '中潜中绩。组织的中坚力量，保持其敬业度。', color: 'text-gray-700', bg: 'bg-gray-50', potential: PotentialLevel.Medium, performance: PerformanceLevel.Medium },
  { id: 'high-impact', title: '高绩效专家 (High Impact)', description: '中潜高绩。在该岗位表现优异，应保持高激励。', color: 'text-indigo-700', bg: 'bg-indigo-50', potential: PotentialLevel.Medium, performance: PerformanceLevel.High },

  // Bottom Row (Low Potential)
  { id: 'underperformer', title: '待改进/淘汰 (Underperformer)', description: '低潜低绩。需考虑调岗或优化淘汰。', color: 'text-red-700', bg: 'bg-red-50', potential: PotentialLevel.Low, performance: PerformanceLevel.Low },
  { id: 'effective', title: '稳定贡献者 (Effective)', description: '低潜中绩。表现符合预期，维持现有状态。', color: 'text-slate-700', bg: 'bg-slate-50', potential: PotentialLevel.Low, performance: PerformanceLevel.Medium },
  { id: 'trusted', title: '资深专家 (Trusted)', description: '低潜高绩。经验丰富的专业人士，适合作为导师。', color: 'text-teal-700', bg: 'bg-teal-50', potential: PotentialLevel.Low, performance: PerformanceLevel.High },
];

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: '1',
    name: '陈莎莎',
    role: '高级产品经理',
    department: '产品部',
    avatar: 'https://picsum.photos/100/100?random=1',
    performance: PerformanceLevel.High,
    potential: PotentialLevel.High,
    tenure: 3.5,
    flightRisk: 'Medium',
    lastReviewDate: '2023-12-01',
    keyStrengths: ['战略视野', '领导力', '数据分析'],
    developmentNeeds: ['公众演讲', '授权管理'],
    successionStatus: 'Ready-Future',
    targetRole: '产品总监',
    careerAspiration: '希望在2年内负责一条完整的产品线业务。'
  },
  {
    id: '2',
    name: '李迈克',
    role: '软件工程师 II',
    department: '研发部',
    avatar: 'https://picsum.photos/100/100?random=2',
    performance: PerformanceLevel.Medium,
    potential: PotentialLevel.High,
    tenure: 1.2,
    flightRisk: 'Low',
    lastReviewDate: '2024-01-15',
    keyStrengths: ['代码效率', '创新能力', '团队协作'],
    developmentNeeds: ['系统架构', '文档规范'],
    successionStatus: 'Ready-Future',
    targetRole: '技术专家 (Staff Engineer)',
    careerAspiration: '专注于后端架构深度，成为技术专家。'
  },
  {
    id: '3',
    name: '张杰茜',
    role: '销售副总裁',
    department: '销售部',
    avatar: 'https://picsum.photos/100/100?random=3',
    performance: PerformanceLevel.High,
    potential: PotentialLevel.Medium,
    tenure: 5.0,
    flightRisk: 'High',
    lastReviewDate: '2023-11-20',
    keyStrengths: ['商务谈判', '客户关系', '收入增长'],
    developmentNeeds: ['跨部门协作'],
    successionStatus: 'None',
    targetRole: '',
    careerAspiration: '维持现有高产出，寻求期权激励。'
  },
  {
    id: '4',
    name: '刘路易',
    role: '法务顾问',
    department: '法务部',
    avatar: 'https://picsum.photos/100/100?random=4',
    performance: PerformanceLevel.High,
    potential: PotentialLevel.Low,
    tenure: 8.0,
    flightRisk: 'Low',
    lastReviewDate: '2023-10-05',
    keyStrengths: ['合规性', '风险管理', '细节导向'],
    developmentNeeds: ['情商管理', '灵活性'],
    successionStatus: 'None',
    targetRole: '',
    careerAspiration: '稳定工作，平衡生活。'
  },
  {
    id: '5',
    name: '瑞秋',
    role: '法务助理',
    department: '法务部',
    avatar: 'https://picsum.photos/100/100?random=5',
    performance: PerformanceLevel.Medium,
    potential: PotentialLevel.Medium,
    tenure: 2.0,
    flightRisk: 'Medium',
    lastReviewDate: '2024-02-01',
    keyStrengths: ['调研能力', '组织能力', '敬业精神'],
    developmentNeeds: ['自信心', '法律文书'],
    successionStatus: 'Ready-Future',
    targetRole: '法务顾问',
    careerAspiration: '考取高级律师资格证，独立负责项目。'
  },
  {
    id: '6',
    name: '何伟',
    role: '执行合伙人',
    department: '管理层',
    avatar: 'https://picsum.photos/100/100?random=6',
    performance: PerformanceLevel.High,
    potential: PotentialLevel.High,
    tenure: 10.0,
    flightRisk: 'High',
    lastReviewDate: '2023-12-15',
    keyStrengths: ['交易撮合', '企业战略', '导师精神'],
    developmentNeeds: ['耐心', '工作生活平衡'],
    successionStatus: 'None',
    targetRole: '',
    careerAspiration: '退休或转为顾问。'
  },
  {
    id: '7',
    name: '唐娜',
    role: '首席运营官',
    department: '运营部',
    avatar: 'https://picsum.photos/100/100?random=7',
    performance: PerformanceLevel.High,
    potential: PotentialLevel.Medium,
    tenure: 12.0,
    flightRisk: 'Low',
    lastReviewDate: '2023-11-01',
    keyStrengths: ['运营管理', '识人能力', '效率提升'],
    developmentNeeds: ['技术理解力'],
    successionStatus: 'None',
    targetRole: '执行合伙人',
    careerAspiration: '接任公司一把手位置。'
  },
  {
    id: '8',
    name: '哈罗德',
    role: '初级专员',
    department: '法务部',
    avatar: 'https://picsum.photos/100/100?random=8',
    performance: PerformanceLevel.Low,
    potential: PotentialLevel.Medium,
    tenure: 0.8,
    flightRisk: 'Low',
    lastReviewDate: '2024-03-01',
    keyStrengths: ['积极性', '忠诚度'],
    developmentNeeds: ['细节把控', '抗压能力'],
    successionStatus: 'None',
    targetRole: '法务助理',
    careerAspiration: '快速适应职场。'
  },
  {
    id: '9',
    name: '卡特琳娜',
    role: '高级顾问',
    department: '法务部',
    avatar: 'https://picsum.photos/100/100?random=9',
    performance: PerformanceLevel.High,
    potential: PotentialLevel.High,
    tenure: 4.0,
    flightRisk: 'Medium',
    lastReviewDate: '2023-12-10',
    keyStrengths: ['逻辑思维', '执行力', '忠诚度'],
    developmentNeeds: ['软技能'],
    successionStatus: 'Ready-Now',
    targetRole: '法务合伙人',
    careerAspiration: '成为事务所最年轻的合伙人。'
  }
];
